### ISSUE TITLE
Motor controllers bug in simulation

### ISSUE THREAD

**Issue by mihaelapopescu** [KovaxG/BattleLabRobotica#1]
As stated in the Program class, the right wheel should turn when the param `nr == 1`.
```
protected void motorControl(int nr, float speed) {
    if (nr == 1) robot.rWheelForce = speed;
    else         robot.lWheelForce = speed;
```
The problem is that the left wheel turns instead and I didn't find the cause. 
Any idea, @KovaxG?

**Comment by KovaxG** [comment]
Whoops. fixed :)
